### ISSUE TITLE
<class 'ModuleNotFoundError'>: No module named 'numba'

### ISSUE THREAD

**Issue by boud123** [HarryvL/fcFEM-basic#13]
13:39:10  Traceback (most recent call last):
  File "C:/Users/boude/AppData/Roaming/FreeCAD/Macro/fcFEM.FCMacro", line 48, in <module>
    import femTools as ft
  File "C:\Users\boude\Desktop\FreeCAD-portable\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\boude\AppData\Roaming\FreeCAD\Macro\femTools.py", line 31, in <module>
    from numba import jit
  File "C:\Users\boude\Desktop\FreeCAD-portable\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'numba'

**Comment by HarryvL** [comment]
See updated README file for dependencies and how to install them
